/**
 *
 */
package vn.chuyenviet.sdk.web.demo.utils

/**
 * @author HaiNT
 */
object ApplicationMessage {
    const val ERROR = "ERROR"
    const val DUPLICATE_EMAIL = "duplicate-email"
    const val DUPLICATE_RECOMMENDED_EMAIL = "duplicate-recommended-email"
    const val UNAUTHORISED = "unauthorized"
    const val LOGIN_FAIL = "LOGIN FAIL"
    const val REGISTER_FAIL = "REGISTER FAIL"
    const val NOT_FOUND_EXCEPTION = "not-found-exception"
    const val NOT_FOUND = "not-found"
    const val SUCCESS = "SUCCESS"
    const val FAIL = "FAIL"
    const val DELETE_FAIL = "delete-fail"
    const val USER_ID_NULL = "user-id-null"
    const val USER_EMAIL_NULL = "user-email-null"
    const val USER_EMAIL_EXIST = "user-email-exist"
    const val EMAIL_DOES_NOT_EXIST = "email-does-not-exist"
    const val USER_NOT_EXIST = "user-not-exist"
    const val USER_FIRST_NULL = "user-firstname-null"
    const val USER_LAST_NULL = "user-lastname-null"
    const val USER_USERNAME_NULL = "user-username-null"
    const val FUNCTION_NAME_NULL = "function-name-null"
    const val FUNCTION_AUTORITYKEY_NULL = "function-autoritykey-null"
    const val FUNCTIONROLE_AUTHORITYID_NULL = "functionrole-functionid-null"
    const val FUNCTIONUSER_USERID_NULL = "functionuser-userid-null"
    const val FUNCTIONUSER_FUNCTIONID_NULL = "functionuser-functionid-null"
    const val AUTHORITY_NAME_NULL = "authority-name-null"
    const val ORGANIZATION_CODE_NULL = "organization-code-null"
    const val ORGANIZATION_CREATEDFOR_NULL = "organization-createfor-null"
    const val WHISTORY_ENTITYTYPE_NULL = "whistory-entitytype-null"
    const val WHISTORY_ENTITYID_NULL = "whistory-entityid-null"
    const val WHISTORY_ACTEDBY_NULL = "whistory-actedby-null"
    const val WHISTORY_ACTEDON_NULL = "whistory-actedon-null"
    const val WHISTORY_ENTITYSTATUS_NULL = "whistory-entitystatus-null"
    const val WHISTORY_COMMENT_RANGE_0_255 = "content-whistory-comment-range-0-255"
    const val WHISTORY_DIFF_RANGE_0_65535 = "content-whistory-diff-range-0-65535"
    const val CANNOT_REGISTER_USER = "cannot-register-user"
    const val USERNAME_PASSWORD_INCORRECT = "username-password-incorrect"
    const val WRONG_EMAIL = "common-email-wrong"
    const val WRONG_APIKEY = "common-api-key-wrong"
    const val DATE_IN_PAST = "date-must-not-be-in-the-past"
    const val UPLOAD_FILE_REQUIRE = "upload-file-required"
    const val ACCOUNT_DISABLE_TRANSACTION = "account-disable-transaction"
    const val ACCOUNT_INACTIVE = "account-is-inactive"
    const val ACCOUNT_NOT_FOUND = "account-not-found"
    const val ACCOUNT_BALANCE_NOT_RIGHT = "dont-enough-money"
    const val INVALID_REQUEST_PARAM = "request-params-invalid"
    const val EMPTY = "response-data-empty"
    const val NOT_ACCEPTABLE = "NOT_ACCEPTABLE"
    const val EMAIL_INVALID = "email-invalid"
    const val PHONE_INVALID = "phone-invalid"
    const val WRONG_FORMAT = "wrong-format"
    const val UPLOAD_AVATAR_TYPE = "upload-avatar-must-png-or-jpg"
    const val DONT_HAVE_PERMISSION_ON_THAT_ITEM = "you-dont-have-permission-on-one-of-these-function"

    // CITY
    const val CITY_NAME_NULL = "city-name-null"
    const val CITY_COUNTRYID_NULL = "city-countryid-null"
    const val CITY_REGION_COUNTRY_COUNTRYID_NOT_EXIST = "city-region-country-countryid-not-exist"
    const val CITY_REGION_TIMEZONE_TIMEZONEID_NOT_EXIST = "city-region-timezone-timezoneid-not-exist"
    const val CITY_ORDER_NULL = "city-order-null"
    const val CITY_ISACTIVE_NULL = "city-isactive-null"

    // COUNTRY
    const val COUNTRY_COUNTRYCODE_NULL = "country-countrycode-null"
    const val COUNTRY_NAME_NULL = "country-name-null"
    const val COUNTRY_REGION_TIMEZONE_TIMEZONEID_NOT_EXIST = "country-region-timezone-timezoneid-not-exist"
    const val COUNTRY_ORDER_NULL = "country-order-null"
    const val COUNTRY_ISACTIVE_NULL = "country-isactive-null"

    // DISTRICT
    const val DISTRICT_NAME_NULL = "district-name-null"
    const val DISTRICT_CITYID_NULL = "district-cityid-null"
    const val DISTRICT_REGION_CITY_CITYID_NOT_EXIST = "district-region-city-cityid-not-exist"
    const val DISTRICT_ORDER_NULL = "district-order-null"
    const val DISTRICT_ISACTIVE_NULL = "district-isactive-null"

    // STREET
    const val STREET_NAME_NULL = "street-name-null"
    const val STREET_WARDID_NULL = "street-wardid-null"
    const val STREET_REGION_WARD_WARDID_NOT_EXIST = "street-region-ward-wardid-not-exist"
    const val STREET_ORDER_NULL = "street-order-null"
    const val STREET_ISACTIVE_NULL = "street-isactive-null"
    const val STREET_NOT_EXIST = "street-not-exist"

    // WARD
    const val WARD_NAME_NULL = "ward-name-null"
    const val WARD_DISTRICTID_NULL = "ward-districtid-null"
    const val WARD_REGION_DISTRICT_DISTRICTID_NOT_EXIST = "ward-region-district-districtid-not-exist"
    const val WARD_ORDER_NULL = "ward-order-null"
    const val WARD_ISACTIVE_NULL = "ward-isactive-null"
    const val WARD_NOT_EXIST = "ward-not-exist"

    //USER
    const val USER_ACC_NOT_FOUND = "user-account-not-found"
    const val USER_ACC_NULL = "user-account-null"
    const val USER_ACC_PASS_NULL = "user-account-password-null"
    const val USER_ACC_USER_NAME_NULL = "user-account-username-null"
    const val PHONE_LIMIT20 = "phone-limit-20"
    const val LANGUAGE_LIMIT10 = "language-limit-10"
    const val REGISTRANT_LIMIT50 = "registrant-limit-50"
    const val MODIFIER_LIMIT50 = "modifier-limit-50"
    const val LEVEL_LIMIT10 = "level-limit-10"
    const val QUESTION_TYPE_LIMIT10 = "question-type-limit-10"
    const val CODE_SUBJECT_NULL = "codesubject-null"
    const val USER_ACCOUNT_NULL = "useraccount-null"
    const val GROUP_ID_NULL = "groupid-null"
    const val ROOM_ID_NULL = "roomid-null"
    const val USER_NOT_FOUND = "user-not-found"
    const val ACCOUNT_AVAILABLE = "account-available"
    const val TOKEN_ERROR = "token-error"
}